#ifndef __CONFIG_H__
#define __CONFIG_H__

/* Generated by Kconfig */

/* Drivers */

#define USEING_RGB_DRIVER
/* end of Drivers */

/* Examples */

#define USEING_REG_EXAMPLE
/* end of Examples */

#endif
